"""Script to fetch and process sound data from Amazon Ask Sound Library skill."""

import asyncio
from datetime import UTC, datetime
from pathlib import Path
from typing import Any, cast

import orjson
from aiohttp import ClientSession, ClientTimeout

# URL of the JSON file
url = "https://m.media-amazon.com/images/G/01/mobile-apps/dex/ask-tech-docs/ask-soundlibrary._TTH_.json"
destination_python_filename = "src/aioamazondevices/sounds.py"
destination_strings_filename = "scripts/sounds_strings.json"
destination_services_filename = "scripts/sounds_services.yaml"


async def get_data() -> dict[str, Any]:
    """Get data from URL."""
    async with ClientSession() as session:
        resp = await session.get(url, timeout=ClientTimeout(10))
        return cast("dict[str,Any]", await resp.json())


async def process_data(
    data: dict[str, Any],
) -> tuple[dict[str, Any], dict[str, Any], list[str]]:
    """Process received data."""
    result_python: dict[str, Any] = {}
    result_strings: dict[str, Any] = {}
    result_yaml: list[str] = []
    if "sounds" in data:
        for item in data["sounds"]:
            description: str = item["name"]
            description_root_str: str = description.split("(")[0].strip()
            filename: str = item["audioFilePath"]
            filename_root_str = filename.split("/")[-1][:-3]
            root_count = result_python.get(filename_root_str, 0)
            result_python.update({filename_root_str: root_count + 1})
            result_strings.update({filename_root_str: description_root_str})
            if filename_root_str not in result_yaml:
                result_yaml.append(filename_root_str)

    return result_python, result_strings, result_yaml


async def save_data_python(data: dict[str, Any]) -> None:
    """Save data to sounds.py."""
    data_json = orjson.dumps(
        data,
        option=orjson.OPT_INDENT_2 | orjson.OPT_SORT_KEYS,
    ).decode("utf-8")
    today = datetime.now(UTC).strftime("%Y-%m-%d %H:%M")
    with Path.open(
        Path(destination_python_filename), mode="w", encoding="utf-8"
    ) as file:
        file.write(f'"""Generated by update_sounds_list.py [{today}]."""\n\n')
        file.write("SOUNDS_LIST = " + data_json)
        file.write("\n")


async def save_data_strings(data: dict[str, Any]) -> None:
    """Save data to sounds_string.json."""
    data_json = orjson.dumps(
        {"selector": {"sound": {"options": data}}},
        option=orjson.OPT_INDENT_2 | orjson.OPT_SORT_KEYS,
    ).decode("utf-8")
    with Path.open(
        Path(destination_strings_filename), mode="w", encoding="utf-8"
    ) as file:
        file.write(data_json)
        file.write("\n")


async def save_data_yaml(data: list[str]) -> None:
    """Save data to sounds_services.yaml."""
    elaborated_data = ""
    data.sort()
    for entry in data:
        elaborated_data = elaborated_data + "            - " + entry + "\n"
    with Path.open(
        Path(destination_services_filename), mode="w", encoding="utf-8"
    ) as file:
        file.write("send_sound:\n")
        file.write("  fields:\n")
        file.write("    sound:\n")
        file.write("      required: true\n")
        file.write("      example: amzn_sfx_doorbell_chime\n")
        file.write("      default: amzn_sfx_doorbell_chime\n")
        file.write("      selector:\n")
        file.write("        select:\n")
        file.write("          options:\n")
        file.write(elaborated_data)
        file.write("          translation_key: sound\n")


async def main() -> None:
    """Script main execution."""
    url_data = await get_data()
    (
        processed_data_python,
        processed_data_strings,
        process_data_yaml,
    ) = await process_data(data=url_data)
    await save_data_python(data=processed_data_python)
    await save_data_strings(data=processed_data_strings)
    await save_data_yaml(data=process_data_yaml)


if __name__ == "__main__":
    asyncio.run(main())
